### ISSUE TITLE
Node version detection is mixed up

### ISSUE THREAD

**Issue by stefanjudis** [twilio-labs/plugin-serverless#21]
I'm using nvm and it's set to switch node versions whenever enter a new dir and a `.nvmrc` is present. I created a new project with `twilio serverless:init`. When I now enter the created dir the node version is changed to `8.10.0` (as my bash prompt shows me).

I now run `twilio serverless:start` and am facing a node version warning because it detects node `10.16.0`. 😲 What's interesting about this is, is that my default nvm node version is `12.4.0`.

Running `node -v` inside of the dir correctly returns `8.10`.

<img width="703" alt="Screenshot 2019-08-08 at 16 20 16" src="https://user-images.githubusercontent.com/962099/62710923-7788e900-b9f8-11e9-9f11-b14261fa2759.png">

This behavior persists across terminal sessions. :) 

Twilio twilio binary is the one installed via brew.

```
🐬  ➡ which twilio                                                                                                                                                                          
/usr/local/bin/twilio
```

Running `twilio-run` in the same directory works fine.

```
/tmp/your-project-name  ⬡ v8.10.0

  ➡ npx twilio-run                                                                                                                                                                           
┌────────────────────────────────────────────────────────────────────┐
│                                                                    │
│   Twilio functions available:                                      │
│   ├── /hello-world | http://localhost:3000/hello-world             │
│   ├── /private-message | http://localhost:3000/private-message     │
│   └── [protected] /sms/reply | http://localhost:3000/sms/reply     │
│                                                                    │
│   Twilio assets available:                                         │
│   ├── /index.html | http://localhost:3000/index.html               │
│   ├── [private] /message.js | Runtime.getAssets()['/message.js']   │
│   └── /style.css | http://localhost:3000/style.css                 │
│                                                                    │
└────────────────────────────────────────────────────────────────────┘
```

**Comment by philnash** [comment]
This has to be something to do with how the CLI installs/references Node itself. If `twilio-run` inside the directory works then `create-twilio-function` and `twilio-run` are both doing their job correctly.

**Comment by philnash** [comment]
This popped into my head, so I went investigating.

When you install the CLI via homebrew [it installs Node 10.16.0 along with it](https://github.com/twilio/homebrew-brew/blob/master/Formula/twilio-cli-node.rb#L4).

We might want some messaging here that if you are running Node on a Mac and you want to write serverless functions and use the CLI then the best way to install it is via npm.

**Comment by childish-sambino** [comment]
Pushed an update to homebrew twilio-cli earlier today (v1.8.3). Try it out and let me know how it goes.

**Comment by stefanjudis** [comment]
Thank you! Looks like it is resolved for me. :)
