### ISSUE TITLE
Unable to activate when only providing source-environment param

### ISSUE THREAD

**Issue by ShelbyZ** [twilio-labs/plugin-serverless#22]
Below is a quick listing of my environment, running the initial activate command without source-environment, and finally with:

![image](https://user-images.githubusercontent.com/1033099/63036640-48e49580-be72-11e9-9634-5afe37d52ef6.png)

It looks like it is trying to check the build-sid that was not provided.  It may be a case where a better error message explaining that what parameters are required would be helpful.

**Comment by dkundel** [comment]
That's great feedback!

We'll be renaming the command to promote soon (it's already an alias). And you need to specify an environment to promote to. So --environment should be marked as required. Not sure why it isn't.

Either --source-environment or --build-sid are also required to tell the CLI which build should actually be promoted to the environment.

I'm currently at JSConf US but I'll try to get to that next week. Unless you want to file a PR for this 😊

**Comment by ShelbyZ** [comment]
I had originally thought the code would be in the serverless plugin but it was in twilio-run - https://github.com/twilio-labs/twilio-run/pull/75
