### ISSUE TITLE
Clearly display which asset is unable to be uploaded

### ISSUE THREAD

**Issue by daniel-simpson** [twilio-labs/plugin-serverless#33]
When running `twilio-run deploy` from a twilio serverless template and a few minor changes, I receive an error message with very little detail involved:

![image](https://user-images.githubusercontent.com/4665754/83961088-2e811a00-a8d3-11ea-9fdb-737633334a75.png)

I tracked this down myself (eventually) to the fact that I had a `.gitkeep` file inside of my assets directory (probably a stupid thing to do, and I've since removed the file anyway.

Would it be possible to enhance the twilio-serverless cli plugin to clearly state the name of which asset is unable to be deployed?  Even with debug logging enabled I wasn't able to find this information in the logs.

A big thank you to everyone who has contributed to this project, its a great platform to work on and I'm having loads of fun!

**Comment by philnash** [comment]
Hey @daniel-simpson, thanks for the report. You're right that the error could be more clear, or at least point to the offending asset!

The code for this is actually within the [@twilio-labs/serverless-api](https://github.com/twilio-labs/serverless-api) project ([here, to be exact](https://github.com/twilio-labs/serverless-api/blob/6dc1bc43e7516d816a976ea190e7fc4b35a12f3f/src/api/assets.ts#L162)). So I'm going to open an issue over there and look to fix it this week.

**Comment by daniel-simpson** [comment]
If you're swamped I can take a look at opening a pull request.  You've done the hardest bit by finding where that error gets fired from.

Thanks for the quick response @philnash, much appreciated

**Comment by daniel-simpson** [comment]
FYI I've [opened a PR](https://github.com/twilio-labs/serverless-api/pull/48) for the above.  Thanks again for the quick response!

**Comment by philnash** [comment]
Thanks for the PR! Sorry it took longer to approve it, but it's all in now and will be released soon.
