### ISSUE TITLE
Add support for `-l` flag within twilio serverless:init

### ISSUE THREAD

**Issue by adamchasetaylor** [twilio-labs/plugin-serverless#36]
The error below seems to be caused by something else in Twilio CLI, but it is confusing that the error points towards using "-l" to troubleshoot when "-l" is not implemented for init.

PS /Users/adtaylor/work/twilio-serverless/test_assets/MP3TEST>twilio serverless:init example-client-app --template="voice-client-javascript"
» twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
» Error: EEXIT: 1
» Code: EEXIT

PS /Users/adtaylor/work/twilio-serverless/test_assets/MP3TEST>twilio serverless:init example-client-app --template="voice-client-javascript" -l debug
» Error: Unexpected arguments: -l, debug
» See more help with --help

PS /Users/adtaylor/work/twilio-serverless/test_assets/MP3TEST> twilio serverless:init --help  

Creates a new Twilio Function project

USAGE

 $ twilio serverless:init NAME

ARGUMENTS

 NAME Name of Serverless project and directory that will be created

OPTIONS

 -a, --account-sid=account-sid The Account SID for your Twilio account
 -p, --profile=profile Shorthand identifier for your profile.
 -t, --auth-token=auth-token Your Twilio account Auth Token
 --empty Initialize your new project with empty functions and assets directories
 --import-credentials  Import credentials from the environment variables TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN
 --skip-credentials  Don't ask for Twilio account credentials or import them from the environment
 --template=template Initialize your new project with a template from github.com/twilio-labs/function-templates
 --typescript  Initialize your Serverless project with TypeScript

**Comment by philnash** [comment]
The error that recommends using `-l` is from the Twilio CLI and is a generic one based on an unhandled error. It might be worth raising something with the CLI itself for errors from plugins that don't necessarily implement the same flags.

It is possibly a good idea to implement the `-l` flag for `create-twilio-function` though.

Are you using the latest version of the plugin (should be 1.7.1, check with `twilio plugins`)? If not, can you update with `twilio plugins:update @twilio-labs/plugin-serverless` and try again.

If that's not the problem, can you try the same call with `create-twilio-function` directly?

```
npm init twilio-function example-client-app --template="voice-client-javascript"
```

You might at least get a better error message out of that.

Finally, did you come across this error with a new project or account, or was it from an existing account?

Thanks!

**Comment by adamchasetaylor** [comment]
Fair points. I'm continuing to troubleshoot the issue with the client. It seems to be due to something else in their Windows installation of Node. 

Thanks for the recommendations.
1) Re: Twilio-CLI errors - I'll discuss with CLI folks internally
2) Re: Plugin Version, client is using latest version
3) Re: Trying directly with "create-twilio-function" - great advice - I'll continue down this path with that approach

Closing this request as "-l" would be on create-twilio-function and not within the plugin if I'm understanding your comment correctly.
