### ISSUE TITLE
Issue with environment

### ISSUE THREAD

**Issue by RobertNortonKaptea** [twilio-labs/plugin-serverless#45]
I can not seem to deploy anymore, i keep getting the below error trying to install this plugin. Can somebody advise here i have tried uninstalling, reinstalling nothing is working.

```bash
oberts-iMac-Pro:TomoLive robertnorton$ twilio plugins:install @twilio-labs/plugin-serverless -l debug
warning @twilio-labs/plugin-serverless > @twilio/cli-core > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
warning @twilio-labs/plugin-serverless > twilio-run > @types/is-ci > @types/ci-info@3.1.0: This is a stub types definition. ci-info provides its own type definitions, so you do not need this installed.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request > har-validator@5.1.5: this library is no longer supported
error twilio-run@3.0.1: The engine "node" is incompatible with this module. Expected version ">=12.22.1". Got "12.16.3"
error Found incompatible module.
Installing plugin @twilio-labs/plugin-serverless... failed
    Error: yarn add @twilio-labs/plugin-serverless@latest --non-interactive --mutex=file:/Users/robertnorton/.twilio-cli/yarn.lock --preferred-cache-folder=/Users/robertnorton/.twilio-cli/yarn --check-files exited with code 1
[Error: EACCES: permission denied, open '/Users/robertnorton/.twilio-cli/error.log'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/robertnorton/.twilio-cli/error.log'
}
Roberts-iMac-Pro:TomoLive robertnorton$ 
```

**Comment by philnash** [comment]
Hey, so the important part of this error message is this line:

```
error twilio-run@3.0.1: The engine "node" is incompatible with this module. Expected version ">=12.22.1". Got "12.16.3"
```

The Serverless plugin requires a version of Node.js that is supported in the Twilio Functions runtime, which is currently 12.22.1 or higher. This is to ensure that the local version acts as close to the deployed version as possible.

Please try installing version 12.22.1 (or higher) of Node.js then try to install the plugin again.

**Comment by RobertNortonKaptea** [comment]
Hi Phil,
Thanks for your email.
Still getting errors See below.

```
Roberts-iMac-Pro:~ robertnorton$ twilio plugins:install @twilio-labs/plugin-serverless -l debug

warning @twilio-labs/plugin-serverless > @twilio/cli-core > ***@***.***: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

warning @twilio-labs/plugin-serverless > twilio-run > ngrok > ***@***.***: request has been deprecated, see https://github.com/request/request/issues/3142

warning @twilio-labs/plugin-serverless > twilio-run > ngrok > ***@***.***: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142

warning @twilio-labs/plugin-serverless > twilio-run > ngrok > ***@***.***: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request > ***@***.***: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

warning @twilio-labs/plugin-serverless > twilio-run > ngrok > request > ***@***.***: this library is no longer supported

warning @twilio-labs/plugin-serverless > twilio-run > @types/is-ci > @***@***.***: This is a stub types definition. ci-info provides its own type definitions, so you do not need this installed.

warning Error running install script for optional dependency: "/Users/robertnorton/.twilio-cli/node_modules/keytar: Command failed.

Exit code: 1

Command: prebuild-install || node-gyp rebuild

Arguments:

Directory: /Users/robertnorton/.twilio-cli/node_modules/keytar

Output:

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=darwin)

gyp info it worked if it ends with ok

gyp info using ***@***.***

gyp info using ***@***.*** | darwin | x64

gyp info find Python using Python version 2.7.16 found at \"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\"

gyp http GET https://nodejs.org/download/release/v14.17.0/node-v14.17.0-headers.tar.gz

gyp http 200 https://nodejs.org/download/release/v14.17.0/node-v14.17.0-headers.tar.gz

gyp http GET https://nodejs.org/download/release/v14.17.0/SHASUMS256.txt

gyp http 200 https://nodejs.org/download/release/v14.17.0/SHASUMS256.txt

gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python

gyp info spawn args [

gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',

gyp info spawn args   'binding.gyp',

gyp info spawn args   '-f',

gyp info spawn args   'make',

gyp info spawn args   '-I',

gyp info spawn args   '/Users/robertnorton/.twilio-cli/node_modules/keytar/build/config.gypi',

gyp info spawn args   '-I',

gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',

gyp info spawn args   '-I',

gyp info spawn args   '/Users/robertnorton/Library/Caches/node-gyp/14.17.0/include/node/common.gypi',

gyp info spawn args   '-Dlibrary=shared_library',

gyp info spawn args   '-Dvisibility=default',

gyp info spawn args   '-Dnode_root_dir=/Users/robertnorton/Library/Caches/node-gyp/14.17.0',

gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',

gyp info spawn args   '-Dnode_lib_file=/Users/robertnorton/Library/Caches/node-gyp/14.17.0/<(target_arch)/node.lib',

gyp info spawn args   '-Dmodule_root_dir=/Users/robertnorton/.twilio-cli/node_modules/keytar',

gyp info spawn args   '-Dnode_engine=v8',

gyp info spawn args   '--depth=.',

gyp info spawn args   '--no-parallel',

gyp info spawn args   '--generator-output',

gyp info spawn args   'build',

gyp info spawn args   '-Goutput_dir=.'

gyp info spawn args ]

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.



No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.



No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.



gyp: No Xcode or CLT version detected!

gyp ERR! configure error

gyp ERR! stack Error: `gyp` failed with exit code: 1

gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)

gyp ERR! stack     at ChildProcess.emit (events.js:376:20)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

gyp ERR! System Darwin 19.6.0

gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"

gyp ERR! cwd /Users/robertnorton/.twilio-cli/node_modules/keytar

gyp ERR! node -v v14.17.0

gyp ERR! node-gyp -v v5.1.0

gyp ERR! not ok"

error An unexpected error occurred: "EACCES: permission denied, open '/Users/robertnorton/.twilio-cli/package.json'".

Installing plugin @twilio-labs/plugin-serverless... failed

    Error: yarn add @***@***.*** --non-interactive

    --mutex=file:/Users/robertnorton/.twilio-cli/yarn.lock

    --preferred-cache-folder=/Users/robertnorton/.twilio-cli/yarn

    --check-files exited with code 1

[Error: EACCES: permission denied, open '/Users/robertnorton/.twilio-cli/error.log'] {

  errno: -13,

  code: 'EACCES',

  syscall: 'open',

  path: '/Users/robertnorton/.twilio-cli/error.log'
```

**Comment by philnash** [comment]
Looks like in this case that keytar failed to install due to problems with node-gyp.

Just before the error is thrown I can see the log:

```
gyp: No Xcode or CLT version detected!
```

So it looks like you may need to install the XCode command line tools. You can do that with the following command in your terminal:

```
xcode-select --install
```

Try running that, then installing the serverless plugin again.

**Comment by RobertNortonKaptea** [comment]
Hi Phil,
Getting there, now getting the below smaller error.


error An unexpected error occurred: "EACCES: permission denied, open '/Users/robertnorton/.twilio-cli/package.json'".

Installing plugin @twilio-labs/plugin-serverless... failed

    Error: yarn add @***@***.*** --non-interactive

    --mutex=file:/Users/robertnorton/.twilio-cli/yarn.lock

    --preferred-cache-folder=/Users/robertnorton/.twilio-cli/yarn

    --check-files exited with code 1

[Error: EACCES: permission denied, open '/Users/robertnorton/.twilio-cli/error.log'] {

  errno: -13,

  code: 'EACCES',

  syscall: 'open',

  path: '/Users/robertnorton/.twilio-cli/error.log'

}

Roberts-iMac-Pro:~ robertnorton$






[A screenshot of a cell phone  Description automatically generated]<https://www.kaptea.io/>


From: Phil Nash ***@***.***>
Date: Wednesday, 9 June 2021 at 07:36
To: twilio-labs/plugin-serverless ***@***.***>
Cc: Robert Norton ***@***.***>, Author ***@***.***>
Subject: Re: [twilio-labs/plugin-serverless] Issue with environment (#45)

Looks like in this case that keytar failed to install due to problems with node-gyp.

Just before the error is thrown I can see the log:

gyp: No Xcode or CLT version detected!

So it looks like you may need to install the XCode command line tools. You can do that with the following command in your terminal:

xcode-select --install

Try running that, then installing the serverless plugin again.

**Comment by philnash** [comment]
This is a permissions issue with the `/Users/robertnorton/.twilio-cli` directory (though I'm not sure how that would have happened).

Try updating the permissions like:

```bash
chmod -R 755 /Users/robertnorton/.twilio-cli
```

You may need to `sudo` that command.

**Comment by philnash** [comment]
Err... that might not be exactly right. Most of the files within `~/.twilio-cli` only need to be 644 (rw-r--r--). Command line permissions aren't my forte, but more permission will at least let you complete the installation even if it's not locked down to the minimum it actually needs.

**Comment by RobertNortonKaptea** [comment]
Hi Phil,
Tried both but getting the below each time.




Roberts-iMac-Pro:~ robertnorton$ sudo chmod -R 755 /Users/robertnorton/.twilio-cli

Password:

Roberts-iMac-Pro:~ robertnorton$ twilio plugins:install @twilio-labs/plugin-serverless

warning Skipping preferred cache folder "/Users/robertnorton/.twilio-cli/yarn" because it is not writable.

warning Selected the next writable cache folder in the list, will be "/Users/robertnorton/Library/Caches/Yarn".

error An unexpected error occurred: "EACCES: permission denied, open '/Users/robertnorton/.twilio-cli/package.json'".

Installing plugin @twilio-labs/plugin-serverless... failed

    Error: yarn add @***@***.*** --non-interactive

    --mutex=file:/Users/robertnorton/.twilio-cli/yarn.lock --preferred-cache-folder=/Users/robertnorton/.twilio-cli/yarn

    --check-files exited with code 1

[Error: EACCES: permission denied, open '/Users/robertnorton/.twilio-cli/error.log'] {

  errno: -13,

  code: 'EACCES',

  syscall: 'open',

  path: '/Users/robertnorton/.twilio-cli/error.log'

}











Roberts-iMac-Pro:~ robertnorton$ chmod -R 755 /Users/robertnorton/.twilio-cli

Roberts-iMac-Pro:~ robertnorton$ twilio plugins:install @twilio-labs/plugin-serverless

warning Skipping preferred cache folder "/Users/robertnorton/.twilio-cli/yarn" because it is not writable.

warning Selected the next writable cache folder in the list, will be "/Users/robertnorton/Library/Caches/Yarn".

error An unexpected error occurred: "EACCES: permission denied, open '/Users/robertnorton/.twilio-cli/package.json'".

Installing plugin @twilio-labs/plugin-serverless... failed

    Error: yarn add @***@***.*** --non-interactive

    --mutex=file:/Users/robertnorton/.twilio-cli/yarn.lock --preferred-cache-folder=/Users/robertnorton/.twilio-cli/yarn

    --check-files exited with code 1

[Error: EACCES: permission denied, open '/Users/robertnorton/.twilio-cli/error.log'] {

  errno: -13,

  code: 'EACCES',

  syscall: 'open',

  path: '/Users/robertnorton/.twilio-cli/error.log'

}







[A screenshot of a cell phone  Description automatically generated]<https://www.kaptea.io/>


From: Phil Nash ***@***.***>
Date: Wednesday, 9 June 2021 at 08:08
To: twilio-labs/plugin-serverless ***@***.***>
Cc: Robert Norton ***@***.***>, Author ***@***.***>
Subject: Re: [twilio-labs/plugin-serverless] Issue with environment (#45)

This is a permissions issue with the /Users/robertnorton/.twilio-cli directory (though I'm not sure how that would have happened).

Try updating the permissions like:

chmod -R 755 /Users/robertnorton/.twilio-cli

You may need to sudo that command.

**Comment by philnash** [comment]
What are the file permissions (`ls -la`) inside your `~/.twilio-cli` directory right now?

**Comment by RobertNortonKaptea** [comment]
Hi phil,
Please see below.





[A screenshot of a cell phone  Description automatically generated]<https://www.kaptea.io/>


From: Phil Nash ***@***.***>
Date: Wednesday, 9 June 2021 at 08:14
To: twilio-labs/plugin-serverless ***@***.***>
Cc: Robert Norton ***@***.***>, Author ***@***.***>
Subject: Re: [twilio-labs/plugin-serverless] Issue with environment (#45)

What are the file permissions (ls -la) inside your ~/.twilio-cli directory right now?

**Comment by RobertNortonKaptea** [comment]
Sorry below.



Roberts-iMac-Pro:.twilio-cli robertnorton$ ls -la

total 784

drwxr-xr-x   10 robertnorton  staff     320  9 Jun 08:10 .

drwxr-xr-x+ 105 robertnorton  staff    3360  8 Jun 08:51 ..

-rwxr-xr-x@   1 robertnorton  staff    8196  7 Jun 10:43 .DS_Store

-rwxr-xr-x    1 root          staff    3585  7 Jun 09:03 error.log

drwxr-xr-x  467 robertnorton  staff   14944  9 Jun 08:10 node_modules

-rwxr-xr-x    1 root          staff      97  7 Jun 09:03 package.json

-rwxr-xr-x    1 robertnorton  staff      58  8 Jun 08:52 version

drwxr-xr-x    3 root          staff      96  7 Jun 08:57 yarn

-rwxr-xr-x@   1 robertnorton  staff  192301  9 Jun 08:10 yarn-error.log

-rwxr-xr-x    1 robertnorton  staff  182523  9 Jun 07:22 yarn.lock

Roberts-iMac-Pro:.twilio-cli robertnorton$






[A screenshot of a cell phone  Description automatically generated]<https://www.kaptea.io/>


From: Robert Norton ***@***.***>
Date: Wednesday, 9 June 2021 at 08:15
To: twilio-labs/plugin-serverless ***@***.***>, twilio-labs/plugin-serverless ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [twilio-labs/plugin-serverless] Issue with environment (#45)
Hi phil,
Please see below.





[A screenshot of a cell phone  Description automatically generated]<https://www.kaptea.io/>


From: Phil Nash ***@***.***>
Date: Wednesday, 9 June 2021 at 08:14
To: twilio-labs/plugin-serverless ***@***.***>
Cc: Robert Norton ***@***.***>, Author ***@***.***>
Subject: Re: [twilio-labs/plugin-serverless] Issue with environment (#45)

What are the file permissions (ls -la) inside your ~/.twilio-cli directory right now?

**Comment by philnash** [comment]
Ah, looks like some of the files are owned by `root` instead of your user. I can never remember the syntax for `chown` but if you can change them from `root` to your user, you might get access back and be able to install.

**Comment by RobertNortonKaptea** [comment]
Hi Phil,
Yeap that’s worked perfectly many thanks for your help.





[A screenshot of a cell phone  Description automatically generated]<https://www.kaptea.io/>


From: Phil Nash ***@***.***>
Date: Wednesday, 9 June 2021 at 08:19
To: twilio-labs/plugin-serverless ***@***.***>
Cc: Robert Norton ***@***.***>, Author ***@***.***>
Subject: Re: [twilio-labs/plugin-serverless] Issue with environment (#45)

Ah, looks like some of the files are owned by root instead of your user. I can never remember the syntax for chown but if you can change them from root to your user, you might get access back and be able to install.

**Comment by philnash** [comment]
Awesome! Glad it's all working again!
